### ISSUE TITLE
Better define extension dependencies

### ISSUE THREAD

**Issue by DavidLemayian** [CodeForAfrica/ckanext-openafrica#22]
Should openAFRICA depend on other extensions, we should provide an easy way to define them here so that deployment is a lot more streamlined.

**Comment by shemogumbe** [comment]
I tend to believe adding an extension is all about adding it to the plugins in the production.ini file, I guess this is easy already, do you suggest automating this process @DavidLemayian ?

**Comment by DavidLemayian** [comment]
@shemogumbe I think this is just beyond adding it to the plugins variable but also installing it so we should probably have this issue as part of https://github.com/CodeForAfricaLabs/openAFRICA instead.
