### ISSUE TITLE
Better social share meta tags info

### ISSUE THREAD

**Issue by DavidLemayian** [CodeForAfrica/ckanext-openafrica#24]
When sharing a dataset link, the social sharing meta tags should include a more appropriate title + description, e.g of the dataset/page title + short description.

**Comment by edmondatto** [comment]
@DavidLemayian All the code that needs to get altered to improve the social meta tags info situation is in ckan and not ckanext-openafrica. As such, shouldn't this issue be on the CodeForAfricaLabs/ckan repo?

**Comment by DavidLemayian** [comment]
@edmondatto Hmm.. Have you seen this? - https://github.com/CodeForAfrica/ckanext-openafrica/blob/master/ckanext/openafrica/templates/base.html#L3

**Comment by edmondatto** [comment]
@DavidLemayian I see that. Would it be better then to use og: meta tags for Twitter, Facebook and G+ in https://github.com/CodeForAfrica/ckanext-openafrica/blob/master/ckanext/openafrica/templates/base.html as opposed to modifying the share url params in https://github.com/CodeForAfricaLabs/ckan/blob/master/ckan/templates/snippets/social.html#L10 ?


Below is the result of a modification I had made to the twitter share url in social.html

<img width="703" alt="screen shot 2017-09-11 at 13 59 33" src="https://user-images.githubusercontent.com/11648960/30271565-7fdb6624-96f9-11e7-8f74-d7438bc69519.png">

**Comment by DavidLemayian** [comment]
@edmondatto I like both suggestions so I've gone ahead to create the issues on this plugin for development and eventual inclusion here - https://github.com/CodeForAfricaLabs/ckanext-social
