### ISSUE TITLE
Update the documentation for installing ckanext-openafrica.

### ISSUE THREAD

**Issue by andela-onnenanya** [CodeForAfrica/ckanext-openafrica#25]
Currently:
The README does not have any instruction on installing the extension. In fact, it ends with 'then', leaving the reader with the expectation of more details.

**Comment by andela-onnenanya** [comment]
@DavidLemayian Can I work on this?

**Comment by DavidLemayian** [comment]
@andela-onnenanya Definitely. Send me a PR when ready.

**Comment by andela-onnenanya** [comment]
This issue should be closed, The PR has been merged. @shemogumbe
