### ISSUE TITLE
Register button not present until you visit the Login page

### ISSUE THREAD

**Issue by ignatiusukwuoma** [CodeForAfrica/ckanext-openafrica#30]
### Currently:
When you install the Open-Africa extension, the `Register` button is absent at the top right side of the page where it is found without the extension. However, clicking on `Log in`  takes you to the Login page where you can find the `Create an account` button. 

### Desired behaviour: 
The `Register` button should be present on the page header beside the `Log in` button so that users can easily find it when they need it.

### Why this issue is important:
Most users will expect to find a register button on the Homepage and might not think that they need to visit the Login page in order to find the `Register` button

**Comment by DavidLemayian** [comment]
@andela-iukwuoma Sounds good. Send me some options what this would look like from using Chrome's developer tools for quick edits of the HTML live page.

**Comment by ignatiusukwuoma** [comment]
OK @DavidLemayian. This is what it would look like on africaopendata.org

![screen shot 2017-09-13 at 1 19 51 pm](https://user-images.githubusercontent.com/26964086/30377152-ab03a788-9886-11e7-9fe5-86d78b3f38cf.png)


This is what it looks like on my CKAN Instance

![screen shot 2017-09-13 at 1 19 22 pm](https://user-images.githubusercontent.com/26964086/30377205-dcff23de-9886-11e7-9c7b-0ab438371777.png)

**Comment by DavidLemayian** [comment]
This looks like a good idea @andela-iukwuoma. Looking forward to the PR.

**Comment by ignatiusukwuoma** [comment]
The PR for this issue is waiting for review @DavidLemayian
