### ISSUE TITLE
CkanUrlException Error Issues with ckanext-openafrica and CKAN 2.8

### ISSUE THREAD

**Issue by tchnlgst** [CodeForAfrica/ckanext-openafrica#48]
Greetings,

I have ckanext-openafrica running well under CKAN 2.7 in a test environment. Since they're now on version 2.9, I decided to move up one level to CKAN 2.8. Ckanext-openafrica and ckan 2.8 don't seem to get along. :)

I'm getting errors when logging into the user dashboard:

 ```
 File "/usr/lib/ckan/default/src/ckanext-openafrica/ckanext/openafrica/templates/header.html", line 49, in block "header_wrapper"
    <a href="{{ h.url_for(controller='user', action='dashboard') }}">Control Panel</a>
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/helpers.py", line 332, in url_for
    return _local_url(my_url, locale=locale, **kw)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/helpers.py", line 537, in _local_url
    raise ckan.exceptions.CkanUrlException(error)
CkanUrlException: There is a broken url being created {'action': 'dashboard', 'controller': 'user'}
```
----------------------------------------

Looking at the code the error seems to be triggered triggered by this bit in function _local_url under section lines 535-539 of  helpers.py, which is as follows:

    if url == '/packages':
        error = 'There is a broken url being created %s' % kw
        raise ckan.exceptions.CkanUrlException(error)

    return url

Any thoughts on how to get around it?

**Comment by kilemensi** [comment]
Hey @tchnlgst 

As you may have guessed by now, openAFRICA is still running CKAN [2.7](https://open.africa/api/util/status). We are also _very_ interested in upgrading it to the latest CKAN release but we just haven't gotten around to it yet.

Looking at v2.8 [changelog](https://docs.ckan.org/en/2.9/changelog.html#v-2-8-0-2018-05-09) looks like there were a lot of changes that could cause the above, among them:

* **Major Changes**: New Flask blueprints migrated from old Pylons controllers: user, dashboard, feeds, admin and home (#3927, #3870, #3775, #3762)
* **Minor Changes**: Standardize on url_for (#3831)

Please start there and let us know what you find.

**Comment by tchnlgst** [comment]
Thank you for your response.

I posted the same question under the ckan issues list, and they were kind enough to respond. They let me know that:

The syntax for url_for changed as the different controllers were moved to Flask blueprints, instead of url_for(controller=controller, action=action) you need url_for(blueprint.view_function). Most cases are backwards compatible but this particular one is different because there is a new blueprint for dashboards. 

They suggested that I update the code to:

`<a href="{{ h.url_for('dashboard.index') }}">Control Panel</a>`

So I've done so under /usr/lib/ckan/default/src/ckanext-openafrica/ckanext/openafrica/templates/header.html

from:
`<a href="{{ h.url_for(controller='user', action='dashboard') }}">Control Panel</a>`

to:
`<a href="{{ h.url_for('dashboard.index') }}">Control Panel</a>`

That seems to fix the issue. Thank you.
